import type { Employee } from "@/types/employee";
import type { Department } from "@/types/department";
import type { AttendanceRecord } from "@/types/attendance";
import type { LeaveRequest } from "@/types/leave";
import type { PayrollRun } from "@/types/payroll";
import type { JobRequisition } from "@/types/recruitment";
import type { PerformanceCycle } from "@/types/performance";
import type { HRDocument } from "@/types/document";

export const DUMMY_EMPLOYEES: Employee[] = [
  {
    id: "1",
    employeeCode: "AUR-1042",
    firstName: "Amaka",
    lastName: "Obiora",
    email: "amaka.obiora@aurahr.com",
    phone: "+234 802 314 7712",
    department: "Engineering",
    position: "Senior Frontend Engineer",
    employmentType: "Full-time",
    status: "Active",
    dateJoined: "2022-03-14",
    location: "Lagos, NG",
  },
  {
    id: "2",
    employeeCode: "AUR-1043",
    firstName: "Tunde",
    lastName: "Bakare",
    email: "tunde.bakare@aurahr.com",
    phone: "+234 803 552 1190",
    department: "Product",
    position: "Product Manager",
    employmentType: "Full-time",
    status: "Active",
    dateJoined: "2021-11-02",
    location: "Lagos, NG",
  },
  {
    id: "3",
    employeeCode: "AUR-1044",
    firstName: "Chiamaka",
    lastName: "Eze",
    email: "chiamaka.eze@aurahr.com",
    phone: "+234 701 990 4433",
    department: "People Operations",
    position: "HR Business Partner",
    employmentType: "Full-time",
    status: "On Leave",
    dateJoined: "2020-06-21",
    location: "Abuja, NG",
  },
  {
    id: "4",
    employeeCode: "AUR-1045",
    firstName: "David",
    lastName: "Adeyemi",
    email: "david.adeyemi@aurahr.com",
    phone: "+234 909 221 8801",
    department: "Finance",
    position: "Payroll Analyst",
    employmentType: "Full-time",
    status: "Active",
    dateJoined: "2023-01-09",
    location: "Lagos, NG",
  },
  {
    id: "5",
    employeeCode: "AUR-1046",
    firstName: "Ifeoma",
    lastName: "Nwosu",
    email: "ifeoma.nwosu@aurahr.com",
    phone: "+234 810 774 3320",
    department: "Engineering",
    position: "Backend Engineer",
    employmentType: "Full-time",
    status: "Active",
    dateJoined: "2022-08-30",
    location: "Remote",
  },
  {
    id: "6",
    employeeCode: "AUR-1047",
    firstName: "Segun",
    lastName: "Ogunleye",
    email: "segun.ogunleye@aurahr.com",
    phone: "+234 706 118 2245",
    department: "Sales",
    position: "Account Executive",
    employmentType: "Full-time",
    status: "Active",
    dateJoined: "2021-04-17",
    location: "Port Harcourt, NG",
  },
  {
    id: "7",
    employeeCode: "AUR-1048",
    firstName: "Zainab",
    lastName: "Mohammed",
    email: "zainab.mohammed@aurahr.com",
    phone: "+234 815 662 9901",
    department: "Design",
    position: "Product Designer",
    employmentType: "Contract",
    status: "Active",
    dateJoined: "2023-05-11",
    location: "Abuja, NG",
  },
  {
    id: "8",
    employeeCode: "AUR-1049",
    firstName: "Emeka",
    lastName: "Okonkwo",
    email: "emeka.okonkwo@aurahr.com",
    phone: "+234 802 330 7765",
    department: "Engineering",
    position: "Engineering Manager",
    employmentType: "Full-time",
    status: "Active",
    dateJoined: "2019-09-23",
    location: "Lagos, NG",
  },
  {
    id: "9",
    employeeCode: "AUR-1050",
    firstName: "Bolanle",
    lastName: "Fashola",
    email: "bolanle.fashola@aurahr.com",
    phone: "+234 903 445 1102",
    department: "People Operations",
    position: "Recruiter",
    employmentType: "Full-time",
    status: "Suspended",
    dateJoined: "2022-01-05",
    location: "Lagos, NG",
  },
  {
    id: "10",
    employeeCode: "AUR-1051",
    firstName: "Chukwuemeka",
    lastName: "Ibe",
    email: "chuka.ibe@aurahr.com",
    phone: "+234 708 226 4471",
    department: "Finance",
    position: "Financial Controller",
    employmentType: "Full-time",
    status: "Active",
    dateJoined: "2018-02-19",
    location: "Lagos, NG",
  },
  {
    id: "11",
    employeeCode: "AUR-1052",
    firstName: "Halima",
    lastName: "Suleiman",
    email: "halima.suleiman@aurahr.com",
    phone: "+234 812 993 5567",
    department: "Customer Success",
    position: "Support Lead",
    employmentType: "Full-time",
    status: "Active",
    dateJoined: "2021-07-08",
    location: "Remote",
  },
  {
    id: "12",
    employeeCode: "AUR-1053",
    firstName: "Michael",
    lastName: "Eze",
    email: "michael.eze@aurahr.com",
    phone: "+234 706 552 8834",
    department: "Engineering",
    position: "QA Engineer",
    employmentType: "Intern",
    status: "Active",
    dateJoined: "2024-02-12",
    location: "Lagos, NG",
  },
];

export const DUMMY_DEPARTMENTS: Department[] = [
  {
    id: "1",
    name: "Engineering",
    headOfDepartment: "Emeka Okonkwo",
    employeeCount: 38,
    location: "Lagos, NG",
    description: "Product engineering, platform, and quality assurance.",
  },
  {
    id: "2",
    name: "Product",
    headOfDepartment: "Tunde Bakare",
    employeeCount: 9,
    location: "Lagos, NG",
    description: "Product strategy, discovery, and roadmap execution.",
  },
  {
    id: "3",
    name: "Design",
    headOfDepartment: "Zainab Mohammed",
    employeeCount: 6,
    location: "Abuja, NG",
    description: "Product design, brand, and user research.",
  },
  {
    id: "4",
    name: "People Operations",
    headOfDepartment: "Chiamaka Eze",
    employeeCount: 11,
    location: "Abuja, NG",
    description: "Talent, culture, HR operations, and compliance.",
  },
  {
    id: "5",
    name: "Finance",
    headOfDepartment: "Chukwuemeka Ibe",
    employeeCount: 14,
    location: "Lagos, NG",
    description: "Payroll, financial planning, and reporting.",
  },
  {
    id: "6",
    name: "Sales",
    headOfDepartment: "Segun Ogunleye",
    employeeCount: 22,
    location: "Port Harcourt, NG",
    description: "New business, partnerships, and account growth.",
  },
  {
    id: "7",
    name: "Customer Success",
    headOfDepartment: "Halima Suleiman",
    employeeCount: 17,
    location: "Remote",
    description: "Onboarding, support, and customer retention.",
  },
];

export const DUMMY_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "1",
    employeeId: "1",
    employeeName: "Amaka Obiora",
    date: "2026-07-21",
    clockIn: "08:52",
    clockOut: "17:41",
    status: "Present",
  },
  {
    id: "2",
    employeeId: "2",
    employeeName: "Tunde Bakare",
    date: "2026-07-21",
    clockIn: "09:14",
    clockOut: "18:02",
    status: "Late",
  },
  {
    id: "3",
    employeeId: "3",
    employeeName: "Chiamaka Eze",
    date: "2026-07-21",
    clockIn: null,
    clockOut: null,
    status: "On Leave",
  },
  {
    id: "4",
    employeeId: "5",
    employeeName: "Ifeoma Nwosu",
    date: "2026-07-21",
    clockIn: "08:47",
    clockOut: "17:38",
    status: "Present",
  },
  {
    id: "5",
    employeeId: "6",
    employeeName: "Segun Ogunleye",
    date: "2026-07-21",
    clockIn: null,
    clockOut: null,
    status: "Absent",
  },
];

export const DUMMY_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: "1",
    employeeId: "3",
    employeeName: "Chiamaka Eze",
    leaveType: "Annual Leave",
    startDate: "2026-07-14",
    endDate: "2026-07-25",
    days: 10,
    status: "Approved",
    reason: "Family vacation",
  },
  {
    id: "2",
    employeeId: "9",
    employeeName: "Bolanle Fashola",
    leaveType: "Sick Leave",
    startDate: "2026-07-19",
    endDate: "2026-07-22",
    days: 3,
    status: "Pending",
    reason: "Medical recovery",
  },
  {
    id: "3",
    employeeId: "6",
    employeeName: "Segun Ogunleye",
    leaveType: "Casual Leave",
    startDate: "2026-07-28",
    endDate: "2026-07-29",
    days: 2,
    status: "Pending",
    reason: "Personal matter",
  },
];

export const DUMMY_PAYROLL_RUNS: PayrollRun[] = [
  {
    id: "1",
    period: "June 2026",
    employeesPaid: 116,
    totalAmount: 84250000,
    status: "Completed",
    runDate: "2026-06-28",
  },
  {
    id: "2",
    period: "July 2026",
    employeesPaid: 0,
    totalAmount: 0,
    status: "Draft",
    runDate: "2026-07-28",
  },
];

export const DUMMY_JOB_REQUISITIONS: JobRequisition[] = [
  {
    id: "1",
    title: "Senior Backend Engineer",
    department: "Engineering",
    status: "Interviewing",
    applicants: 42,
    location: "Lagos, NG",
    postedDate: "2026-06-30",
  },
  {
    id: "2",
    title: "People Operations Coordinator",
    department: "People Operations",
    status: "Open",
    applicants: 18,
    location: "Abuja, NG",
    postedDate: "2026-07-08",
  },
  {
    id: "3",
    title: "Enterprise Account Executive",
    department: "Sales",
    status: "Open",
    applicants: 27,
    location: "Remote",
    postedDate: "2026-07-12",
  },
];

export const DUMMY_PERFORMANCE_CYCLES: PerformanceCycle[] = [
  {
    id: "1",
    name: "H1 2026 Review",
    period: "Jan – Jun 2026",
    status: "Completed",
    completionRate: 100,
  },
  {
    id: "2",
    name: "H2 2026 Review",
    period: "Jul – Dec 2026",
    status: "In Progress",
    completionRate: 34,
  },
];

export const DUMMY_DOCUMENTS: HRDocument[] = [
  {
    id: "1",
    name: "Employee Handbook 2026.pdf",
    category: "Policy",
    uploadedBy: "Chiamaka Eze",
    uploadedAt: "2026-01-10",
    sizeKb: 2140,
  },
  {
    id: "2",
    name: "Remote Work Policy.pdf",
    category: "Policy",
    uploadedBy: "Chiamaka Eze",
    uploadedAt: "2026-03-02",
    sizeKb: 640,
  },
  {
    id: "3",
    name: "Offer Letter Template.docx",
    category: "Form",
    uploadedBy: "Bolanle Fashola",
    uploadedAt: "2026-05-19",
    sizeKb: 88,
  },
];

/** Dashboard widget summary numbers. */
export const DASHBOARD_STATS = {
  totalEmployees: 117,
  activeEmployees: 109,
  onLeave: 5,
  payrollStatusLabel: "Processed",
  attendanceRate: 94.2,
  openPositions: 8,
  newApplicants: 63,
  upcomingBirthdays: 4,
};

/** Employee growth over the last 8 months, for the line/area chart. */
export const EMPLOYEE_GROWTH_DATA = [
  { month: "Dec", employees: 94 },
  { month: "Jan", employees: 98 },
  { month: "Feb", employees: 101 },
  { month: "Mar", employees: 103 },
  { month: "Apr", employees: 108 },
  { month: "May", employees: 111 },
  { month: "Jun", employees: 114 },
  { month: "Jul", employees: 117 },
];

/** Attendance trend for the current week, for the bar chart. */
export const ATTENDANCE_TREND_DATA = [
  { day: "Mon", present: 104, absent: 6, late: 7 },
  { day: "Tue", present: 108, absent: 4, late: 5 },
  { day: "Wed", present: 106, absent: 5, late: 6 },
  { day: "Thu", present: 109, absent: 3, late: 5 },
  { day: "Fri", present: 101, absent: 8, late: 8 },
];

/** Headcount distribution across departments, for the pie/donut chart. */
export const DEPARTMENT_DISTRIBUTION_DATA = DUMMY_DEPARTMENTS.map((d) => ({
  name: d.name,
  value: d.employeeCount,
}));

export const UPCOMING_BIRTHDAYS = [
  { id: "1", name: "Ifeoma Nwosu", department: "Engineering", date: "Jul 24" },
  { id: "2", name: "Segun Ogunleye", department: "Sales", date: "Jul 27" },
  { id: "3", name: "Zainab Mohammed", department: "Design", date: "Aug 02" },
  { id: "4", name: "David Adeyemi", department: "Finance", date: "Aug 05" },
];
